### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by tslarkin61** [springernature/boomcatch#65]
I am getting a write ENOTSUP unhandled exception with the following request:

C:\Users\Administrator>boomcatch --port 8090 --host 127.0.0.1
2016-03-16 13:25:54 INFO boomcatch: starting boomcatch in process 5928 with opti
ons:
{
    "port": 8090,
    "host": "127.0.0.1",
    "log": {},
    "workers": 1
}
2016-03-16 13:25:54 INFO boomcatch: worker 3868 started
2016-03-16 13:25:54 INFO boomcatch: listening for 127.0.0.1:8090/beacon
2016-03-16 13:26:07 INFO boomcatch: referer=http://localhost:8088/index.htm user
-agent=Mozilla/5.0 (Windows NT 6.3; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0
address=127.0.0.1[] method=GET url=/beacon?rt.start=navigation&rt.tstart=1458134
761909&rt.cstart=1458134762034&rt.bstart=1458134766092&rt.end=1458134767197&t_re
sp=1619&t_page=3669&t_done=5288&t_other=t_domloaded%7C5276&r=http%3A%2F%2Flocalh
ost%3A8088%2Findex.htm&nt_red_cnt=0&nt_nav_type=1&nt_nav_st=1458134761909&nt_red
_st=0&nt_red_end=0&nt_fet_st=1458134762267&nt_dns_st=1458134762267&nt_dns_end=14
58134762267&nt_con_st=1458134762267&nt_con_end=1458134762267&nt_req_st=145813476
2474&nt_res_st=1458134763528&nt_res_end=1458134763531&nt_domloading=145813476356
3&nt_domint=1458134767033&nt_domcontloaded_st=1458134767092&nt_domcontloaded_end
=1458134767185&nt_domcomp=1458134767189&nt_load_st=1458134767189&nt_load_end=145
8134767194&nt_unload_st=1458134763565&nt_unload_end=1458134763697&u=http%3A%2F%2
Flocalhost%3A8088%2Findex.htm&v=0.9&vis.st=visible&ua.plt=Win32&ua.vnd=
2016-03-16 13:26:07 INFO boomcatch: sending rt.firstbyte:1619|ms
rt.lastbyte:5288|ms
rt.load:5288|ms
navtiming.unload:132|ms
navtiming.response:3|ms
navtiming.dom:3626|ms
navtiming.domContent:93|ms
navtiming.load:5|ms

2016-03-16 13:26:07 ERROR boomcatch: unhandled exception
Error: write ENOTSUP
    at exports._errnoException (util.js:746:11)
    at ChildProcess.target._send (child_process.js:484:28)
    at ChildProcess.target.send (child_process.js:416:12)
    at sendHelper (cluster.js:676:8)
    at send (cluster.js:512:5)
    at cluster.js:488:7
    at SharedHandle.add (cluster.js:99:3)
    at queryServer (cluster.js:480:12)
    at Worker.onmessage (cluster.js:438:7)
    at ChildProcess.<anonymous> (cluster.js:692:8)

My suspicion is that there must have been an issue with my installation of boomcatch. Please advise.

**Comment by philbooth** [comment]
Hey @tslarkin61, thanks for reporting this. I'll try to reproduce it and see what's up later on.

What version of node are you running?

**Comment by tslarkin61** [comment]
Phil,

Thanks for the quick response. I am running v0.12.2 of node.

**Comment by philbooth** [comment]
Okay, I've not been able to reproduce it here but it looks like you're running on Windows, is that right?

I don't have a Windows machine to test on but I'm wondering if you're running into https://github.com/nodejs/node-v0.x-archive/issues/5587, or something like it.

You could maybe try verifying that is the problem by wrapping the contents of the `send` function in `src/forwarders/udp.js` inside a `try...catch`, then logging the error details to the console. If it shows `ENOTSUP` and the process doesn't die, it seems like a similar issue.

I don't fully understand the bug from reading the description and, without a machine to test on, I may be barking up the wrong tree here but you could also see whether adding a line like the following fixes it:

```js
    socket.bind(8091, '127.0.0.1');
```

It needs to go in `src/forwarders/udp.js` at line 53, immediately after the call to `udp.createSocket`. Does that have any effect?

Failing both of those, there's a few things you could try to help narrow down the problem:

1. Check whether the problem still occurs if you load the client test from this repo, see `client/rt-get.html`. You'll need to update the port number to `8090` in `beacon_url`.

2. If you can run it inside a Linux VM, see whether that makes any difference.

3. Upgrade to a newer version of nodejs, if possible. Version 4.3.2 could be a good candidate, it has long-term support.

**Comment by tslarkin61** [comment]
No success with your first two suggestions - process terminates with the same unhandled exception. 

Please advise further on your client/rt-get.html suggestion. No sure of how to access that repository.

I do have access to a Linux VM and can test on that environment. I will also work on upgrading nodejs.

**Comment by philbooth** [comment]
`client/rt-get.html` is just a file inside the boomcatch repository.

If you open it up in your browser, it will load a known compatible version of boomerang and then make a beacon request to a boomcatch instance. You'll need to update the port number in the HTML to `8090` from `8080`.

If boomcatch still fails when you load that file, we can rule out anything related to boomerang and the request data in your case.

**Comment by tslarkin61** [comment]
I tested both rt-get and rt-post and while I did enjoy the video of the ferret jumping into the trash can my error persists causing the process to terminate.

**Comment by tslarkin61** [comment]
I can install the Nodeclipse plugins and debug this if you have a cheat sheet to get me up and running.
