### ISSUE TITLE
auto_xhr causes errors

### ISSUE THREAD

**Issue by Cybermaxs** [springernature/boomcatch#67]
When auto_xhr plugin is activated, there is an error while parsing the request because most of the RT vars are not available or set to 0.
Especially  
        t_resp=0
    t_page=0
    t_done=0

boomcatch logs

2016-06-03 15:06:06 INFO boomcatch: referer= user-agent=Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2756.0 Safar
i/537.36 address=127.0.0.1[] method=GET url=/beacon?rt.start=manual&v=1464957067&vis.st=visible&ua.plt=Win32&ua.vnd=Google+Inc.&dom.doms=1&mem.total=12700000&me
m.used=10000000&scr.xy=1536x864&scr.bpp=24%2F24&scr.orn=0%2Flandscape-primary&scr.dpx=2.5&cpu.cnc=4&scr.mtp=10&bat.lvl=1&dom.ln=15&dom.sz=1719&dom.img=0&dom.scr
ipt=3&dom.script.ext=1&pgu=http%3A%2F%2Flocalhost%3A8080%2Findex.html&restiming=%7B%7D&rt.tstart=1464959165911&rt.bstart=1464959126858&rt.end=1464959165911&t_re
sp=0&t_page=0&t_done=0&r=http%3A%2F%2Flocalhost%3A8080%2Findex.html&r2=&u=http%3A%2F%2Flocalhost%3A8080%2Fbetclic-logo-2.png&http.initiator=xhr&nt_fet_st=146495
9128413.81&nt_dns_st=1464959128413.81&nt_dns_end=1464959128413.81&nt_con_st=1464959128413.81&nt_con_end=1464959128413.81&nt_req_st=1464959128413.81&nt_res_st=14
64959128413.81&nt_res_end=1464959128413.81&nt_domint=1464959165911&nt_load_st=1464959165911&nt_load_end=1464959165911&dom.res=2

2016-06-03 15:06:06 ERROR boomcatch: 400 Invalid data
2016-06-03 15:06:06 ERROR boomcatch: Error: Invalid number
    at assertImpl (C:__git\boomcatch\node_modules\check-types\src\check-types.js:643:19)
    at assertPredicate (C:__git\boomcatch\node_modules\check-types\src\check-types.js:638:9)
    at Object.positive (C:__git\boomcatch\node_modules\check-types\src\check-types.js:632:13)
    at normaliseRtData (C:__git\boomcatch\src\normalise.js:47:24)
    at normalise (C:__git\boomcatch\src\normalise.js:28:13)
    at map (C:__git\boomcatch\src\mappers\statsd.js:49:12)
    at send (C:__git\boomcatch\src\index.js:656:22)
    at emitNone (events.js:80:13)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)

**Comment by hollsk** [comment]
I can't replicate this, but that might be because I'm testing against the latest version of autoxhr and Boomerang, and your issue is from several months ago (sorry about that). 

If this is still a problem you're trying to solve, we can try a few things, firstly making sure we're both using the same version of Boomerang and the AutoXHR plugin - I took mine straight from [SOASTA/boomerang](https://github.com/SOASTA/boomerang). 

The problem might also be solved by running Boomcatch with the "unmapped" mapper instead of the default, if you're using the default: `boomcatch --mapper unmapped` or set in your config. Specifying unmapped will give you everything that was sent from Boomerang as a JSON object, instead of a filtered list. I don't know if that's the problem here because you're getting a value of `0` for those vars, but it's worth trying.

**Comment by hollsk** [comment]
I'm going to close this for now, but please feel free to open a new issue if this is still a problem for you!
