### ISSUE TITLE
Incorrect log value for `boomcatch.listen` in README

### ISSUE THREAD

**Issue by gitgrimbo** [springernature/boomcatch#69]
Using the following as shown in the [README.md#L211](https://github.com/springernature/boomcatch/blame/55daace749e7d819e366ae758dc5f0121fcb8fe4/README.md#L211):

``` js
log: console.log,                         // Defaults to function () {}
```

Causes this error:

```
PATH_TO_PROJECT\node_modules\boomcatch\node_modules\check-types\src\check-types.js:643
            throw new Error(message || 'Assertion failed');
                  ^
Error: Invalid log object
    at assertImpl (PATH_TO_PROJECT\node_modules\boomcatch\node_modules\check-types\src\check-types.js:643:19)
    at assertPredicate (PATH_TO_PROJECT\node_modules\boomcatch\node_modules\check-types\src\check-types.js:638:9)
    at Object.object (PATH_TO_PROJECT\node_modules\boomcatch\node_modules\check-types\src\check-types.js:632:13)
    at verifyLog (PATH_TO_PROJECT\node_modules\boomcatch\src\index.js:191:24)
    at verifyOptions (PATH_TO_PROJECT\node_modules\boomcatch\src\index.js:169:5)
    at Object.exports.listen (PATH_TO_PROJECT\node_modules\boomcatch\src\index.js:130:9)
    at Object.<anonymous> (PATH_TO_PROJECT\index.js:11:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Fix is to change the line to:

``` js
log: console,                               // Defaults to function () {}
```

to reflect the [jsdoc](https://github.com/springernature/boomcatch/blob/ca8dc7181c680bae558b1a168334560587d18a67/src/index.js#L101):

```
 * @option log {object}          Object with `info` and `error` log functions.
```

**Comment by hollsk** [comment]
@gitgrimbo thanks for flagging this - I've implemented your suggestion :-)
